spring.application.name=billFlow
spring.datasource.url=jdbc:postgresql://localhost:5433/billFlow
spring.datasource.username=postgres
spring.datasource.password=riya

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=MySuperSecretKeyForBillFlowProject123456789

server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=riyamprajapati@gmail.com
spring.mail.password=ohtf nmpl atsw fihw

#wnmd lapb uuqe hygx
#ohtf nmpl atsw fihw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true